# Generated by Django 5.1.5 on 2025-03-24 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=2)),
                ('discrimination', models.FloatField(default=1.0)),
                ('difficulty', models.FloatField()),
                ('guessing', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexile', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('hours', models.FloatField()),
                ('is_esl', models.BooleanField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_theta', models.FloatField(default=0.0)),
                ('answered_questions', models.JSONField(default=list)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adaptivetest.questionbank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
