# Generated by Django 5.1.7 on 2025-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptivetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
