# Generated by Django 5.2.3 on 2025-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptivetest', '0002_alter_testsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='antonym',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='unrelated',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
